### PR TITLE
Smart constructor

### PR DESCRIPTION
**Pull request by snoyberg**
@jeffhappily can you test out this branch against your WIP on Stack and see if it works? The advantage of this approach is that we can add more fields in the future without incurring a breaking change. CC @norfairking

### CODE REVIEW

**Comment by jeffhappily** [comment]
Could you add a `setRequest` function? Because it's required here to set the request https://github.com/commercialhaskell/stack/blob/master/src/Network/HTTP/StackClient.hs#L156

**Comment by snoyberg** [comment]
I think you'd either need both a `setRequest` and `getRequest`, or a `modifyRequest`. Am I correct?

**Comment by jeffhappily** [comment]
Yes that's correct

**Comment by snoyberg** [comment]
I've added `modifyRequest`

**Comment by jeffhappily** [comment]
Should you export it at `Network.HTTP.Download` as well? I see that all imports are from there

**Comment by snoyberg** [comment]
Done

**Comment by jeffhappily** [comment]
It works perfectly on Stack

**Pull request merged**
